# Generated by Django 2.2.14 on 2020-11-27 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('estudiantes', '0002_auto_20201127_1459'),
        ('materias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='estudiantes',
            field=models.ManyToManyField(related_name='estudiantes', to='estudiantes.Estudiante'),
        ),
    ]
